from __future__ import annotations

import json
import os
import re
import shutil
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any


class VaultError(RuntimeError):
    """Raised when the requested vault operation cannot be completed."""


@dataclass(frozen=True)
class DoctorFinding:
    level: str
    path: str
    message: str


@dataclass(frozen=True)
class CastRole:
    kind: str
    person: str
    plays: str | None = None


@dataclass(frozen=True)
class ArcBeat:
    arc: str
    episode: str
    status: str
    beat: str
    file: Path


@dataclass(frozen=True)
class LoreFact:
    text: str
    source: str
    file: Path


DEFAULT_PACK = """schema: 1
show:
  name: {show_name}
  eras: []
  genre: speculative fiction
  tone: character-forward, dramatic, collaborative
season:
  number: 1
  episode_count: 10
  theme: "A room discovers what the show wants to become."
  arc_spine:
    - episode_target: 1
      beat: pilot - establish theme
roles:
  - kind: showrunner
    person: showrunner
  - kind: director
    person: director
  - kind: writer
    person: staff-writer
provider:
  default: lmstudio
  fallback: mock
budget:
  max_dollars_per_episode: 5.00
"""

DEFAULT_PEOPLE = {
    "showrunner": """---
schema: 1
slug: showrunner
display_name: Showrunner
roles_eligible: [showrunner]
voice:
  fingerprint: "clear theme, decisive taste, protects the season spine"
  signature_moves:
    - "ties every idea back to the season theme"
beliefs:
  - "A strong episode argues with the season theme."
bio_anchors:
  - "Synthetic starter persona generated by ShowBible."
trait_axes:
  openness: 0.8
  conscientiousness: 0.8
  extraversion: 0.5
  agreeableness: 0.6
  neuroticism: 0.3
---

# Showrunner - relationships

## With Director
Trusts the Director to turn premise into playable scenes.
""",
    "director": """---
schema: 1
slug: director
display_name: Director
roles_eligible: [director]
voice:
  fingerprint: "practical, visual, scene-focused"
  signature_moves:
    - "turns abstract ideas into act breaks"
beliefs:
  - "Conflict belongs on screen, not just in exposition."
bio_anchors:
  - "Synthetic starter persona generated by ShowBible."
trait_axes:
  openness: 0.7
  conscientiousness: 0.7
  extraversion: 0.6
  agreeableness: 0.5
  neuroticism: 0.4
---

# Director - relationships

## With Showrunner
Pushes for playable scenes while honoring the season spine.
""",
    "staff-writer": """---
schema: 1
slug: staff-writer
display_name: Staff Writer
roles_eligible: [writer]
voice:
  fingerprint: "curious, connective, good with reversals"
  signature_moves:
    - "finds the emotional turn inside a scene"
beliefs:
  - "Dialogue should reveal pressure, not explain plot."
bio_anchors:
  - "Synthetic starter persona generated by ShowBible."
trait_axes:
  openness: 0.9
  conscientiousness: 0.6
  extraversion: 0.6
  agreeableness: 0.7
  neuroticism: 0.4
---

# Staff Writer - relationships

## With Director
Offers playable alternatives when a scene stalls.
""",
}


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "show"


def atomic_write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp_name, path)
    finally:
        tmp_path = Path(tmp_name)
        if tmp_path.exists():
            tmp_path.unlink()


def atomic_write_json(path: Path, data: Any) -> None:
    atomic_write_text(path, json.dumps(data, indent=2, sort_keys=True) + "\n")


def read_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def is_vault(path: Path) -> bool:
    return (path / "pack.yaml").is_file()


def discover_vault(start: Path | None = None) -> Path:
    current = (start or Path.cwd()).resolve()
    if current.is_file():
        current = current.parent
    for candidate in [current, *current.parents]:
        if is_vault(candidate):
            return candidate
    raise VaultError("Vault not found. Run inside a ShowBible vault or pass --vault.")


def resolve_vault(path: str | None) -> Path:
    return discover_vault(Path(path)) if path else discover_vault()


def ensure_empty_or_force(path: Path, force: bool) -> None:
    if path.exists() and any(path.iterdir()) and not force:
        raise VaultError(f"Refusing to initialize non-empty directory: {path}")


def init_vault(target: Path, show_name: str | None = None, force: bool = False) -> Path:
    target = target.resolve()
    ensure_empty_or_force(target, force)
    target.mkdir(parents=True, exist_ok=True)

    show = show_name or target.name.replace("-", " ").replace("_", " ").title()
    for directory in [
        "research",
        "people",
        "lore-bible",
        "arcs",
        "episodes",
        ".room/sessions",
        ".room/locks",
        ".room/interventions",
    ]:
        (target / directory).mkdir(parents=True, exist_ok=True)

    atomic_write_text(target / "pack.yaml", DEFAULT_PACK.format(show_name=show))
    atomic_write_text(target / "research" / "sources.md", f"# Sources for {show}\n\n- Seeded locally by ShowBible.\n")
    atomic_write_text(target / "research" / "notes.md", f"# Research Notes for {show}\n\nStarter pack created without external research.\n")
    for slug, content in DEFAULT_PEOPLE.items():
        atomic_write_text(target / "people" / f"{slug}.md", content)
    atomic_write_text(target / "lore-bible" / "canon.md", "# Canon\n\n## Facts\n\n- No canon facts recorded yet.\n")
    atomic_write_text(target / "lore-bible" / "glossary.md", "# Glossary\n\n")
    atomic_write_text(target / "lore-bible" / "relationships.md", "# Relationships\n\n")
    atomic_write_text(
        target / "arcs" / "season-theme.md",
        "---\nschema: 1\nseason: 1\nbeats:\n  - episode_target: 1\n    beat: establish the room's central argument\n    status: planned\n---\n\n# Season Theme\n\nA starter arc for the first season.\n",
    )
    atomic_write_json(target / ".room" / "costs.json", {"episodes": {}, "total_tokens": 0, "total_dollars": 0.0})
    atomic_write_json(target / ".room" / "state.json", {"schema": 1, "status": "initialized"})
    return target


def people(vault: Path) -> list[dict[str, str]]:
    result: list[dict[str, str]] = []
    for path in sorted((vault / "people").glob("*.md")):
        text = path.read_text(encoding="utf-8")
        display = _frontmatter_value(text, "display_name") or path.stem.replace("-", " ").title()
        result.append({"slug": path.stem, "display_name": display})
    return result


def cast_roles(vault: Path) -> list[CastRole]:
    pack = (vault / "pack.yaml").read_text(encoding="utf-8")
    roles_block = _section_lines(pack, "roles:", stop_prefixes=("provider:", "budget:", "season:", "show:"))
    roles: list[CastRole] = []
    current: dict[str, str] | None = None
    for line in roles_block:
        stripped = line.strip()
        if stripped.startswith("- "):
            if current and current.get("person"):
                roles.append(CastRole(current.get("kind", "writer"), current["person"], current.get("plays")))
            current = {}
            stripped = stripped[2:].strip()
        if current is None:
            continue
        if ":" in stripped:
            key, value = stripped.split(":", 1)
            current[key.strip()] = value.strip().strip("\"'")
    if current and current.get("person"):
        roles.append(CastRole(current.get("kind", "writer"), current["person"], current.get("plays")))
    return roles


def infer_episode_id(vault: Path, start: Path | None = None) -> str | None:
    current = (start or Path.cwd()).resolve()
    if current.is_file():
        current = current.parent
    try:
        relative = current.relative_to((vault / "episodes").resolve())
    except ValueError:
        return None
    parts = relative.parts
    return parts[0] if parts else None


def episode_cast_roles(vault: Path, episode_id: str) -> list[CastRole]:
    meta = episode_meta(ensure_episode(vault, episode_id))
    roles = []
    for item in meta.get("cast_overrides", []):
        if isinstance(item, dict) and item.get("person"):
            roles.append(CastRole(str(item.get("kind") or "writer"), str(item["person"]), item.get("plays")))
    return roles


def effective_cast_roles(vault: Path, episode_id: str | None = None) -> list[CastRole]:
    roles = cast_roles(vault)
    if not episode_id:
        return roles
    by_person = {role.person: role for role in roles}
    for role in episode_cast_roles(vault, episode_id):
        by_person[role.person] = role
    return list(by_person.values())


def add_cast_role(vault: Path, role: CastRole) -> None:
    roles = [existing for existing in cast_roles(vault) if existing.person != role.person]
    roles.append(role)
    write_cast_roles(vault, roles)


def remove_cast_role(vault: Path, person_slug: str) -> None:
    roles = [role for role in cast_roles(vault) if role.person != person_slug]
    write_cast_roles(vault, roles)


def add_episode_cast_role(vault: Path, episode_id: str, role: CastRole) -> None:
    roles = [existing for existing in episode_cast_roles(vault, episode_id) if existing.person != role.person]
    roles.append(role)
    write_episode_cast_roles(vault, episode_id, roles)


def remove_episode_cast_role(vault: Path, episode_id: str, person_slug: str) -> None:
    roles = [role for role in episode_cast_roles(vault, episode_id) if role.person != person_slug]
    write_episode_cast_roles(vault, episode_id, roles)


def write_episode_cast_roles(vault: Path, episode_id: str, roles: list[CastRole]) -> None:
    episode = ensure_episode(vault, episode_id)
    meta = episode_meta(episode)
    meta["cast_overrides"] = [
        {"kind": role.kind, "person": role.person, **({"plays": role.plays} if role.plays else {})}
        for role in roles
    ]
    write_episode_meta(episode, meta)


def write_cast_roles(vault: Path, roles: list[CastRole]) -> None:
    pack_path = vault / "pack.yaml"
    pack = pack_path.read_text(encoding="utf-8")
    role_lines = ["roles:"]
    for role in roles:
        role_lines.append(f"  - kind: {role.kind}")
        role_lines.append(f"    person: {role.person}")
        if role.plays:
            role_lines.append(f"    plays: {role.plays}")
    replacement = "\n".join(role_lines)
    atomic_write_text(pack_path, _replace_section(pack, "roles:", replacement, stop_prefixes=("provider:", "budget:")))


def write_person(vault: Path, slug: str, display_name: str, eligible_role: str, plays: str | None = None) -> Path:
    body = f"""---
schema: 1
slug: {slug}
display_name: {display_name}
roles_eligible: [{eligible_role}]
{f"plays: {plays}" if plays else ""}
voice:
  fingerprint: "AI-assisted starter voice; edit this file to sharpen cadence and taste"
  signature_moves:
    - "protects the intent of their assigned role"
beliefs:
  - "Specific choices beat generic output."
bio_anchors:
  - "Created from the ShowBible CLI."
trait_axes:
  openness: 0.6
  conscientiousness: 0.6
  extraversion: 0.6
  agreeableness: 0.6
  neuroticism: 0.4
---

# {display_name} - relationships

## With the room
Starter relationship notes. Replace with researched dynamics as the pack matures.
"""
    path = vault / "people" / f"{slug}.md"
    atomic_write_text(path, body.replace("\n\nvoice:", "\nvoice:"))
    return path


def _section_lines(text: str, header: str, stop_prefixes: tuple[str, ...]) -> list[str]:
    lines = text.splitlines()
    start = next((index for index, line in enumerate(lines) if line.strip() == header), None)
    if start is None:
        return []
    section: list[str] = []
    for line in lines[start + 1 :]:
        if line and not line.startswith(" ") and line.strip().endswith(":") and line.strip() in stop_prefixes:
            break
        section.append(line)
    return section


def _replace_section(text: str, header: str, replacement: str, stop_prefixes: tuple[str, ...]) -> str:
    lines = text.splitlines()
    start = next((index for index, line in enumerate(lines) if line.strip() == header), None)
    if start is None:
        return text.rstrip() + "\n" + replacement + "\n"
    end = len(lines)
    for index in range(start + 1, len(lines)):
        line = lines[index]
        if line and not line.startswith(" ") and line.strip().endswith(":") and line.strip() in stop_prefixes:
            end = index
            break
    return "\n".join([*lines[:start], replacement, *lines[end:]]).rstrip() + "\n"


def _frontmatter_value(text: str, key: str) -> str | None:
    match = re.search(rf"^{re.escape(key)}:\s*(.+)$", text, flags=re.MULTILINE)
    if not match:
        return None
    return match.group(1).strip().strip("\"'")


def ensure_episode(vault: Path, episode_id: str) -> Path:
    episode = vault / "episodes" / episode_id
    for directory in ["writers-room", "drafts"]:
        (episode / directory).mkdir(parents=True, exist_ok=True)
    meta = episode / "meta.json"
    if not meta.exists():
        atomic_write_json(
            meta,
            {
                "schema": 1,
                "episode": episode_id,
                "status": "created",
                "completed_phases": [],
                "phase_events": [],
                "interventions": [],
            },
        )
    return episode


def list_episodes(vault: Path) -> list[str]:
    episodes_dir = vault / "episodes"
    if not episodes_dir.exists():
        return []
    return sorted(path.name for path in episodes_dir.iterdir() if path.is_dir())


def episode_meta(episode: Path) -> dict[str, Any]:
    return read_json(
        episode / "meta.json",
        {
            "schema": 1,
            "episode": episode.name,
            "status": "created",
            "completed_phases": [],
            "phase_events": [],
            "interventions": [],
        },
    )


def write_episode_meta(episode: Path, meta: dict[str, Any]) -> None:
    atomic_write_json(episode / "meta.json", meta)


def append_transcript_entry(path: Path, author: str, role: str, body: str, intervention: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        atomic_write_text(path, "---\nschema: 1\n---\n\n")
    stamp = _next_stamp(path)
    suffix = ", intervention" if intervention else ""
    existing = path.read_text(encoding="utf-8")
    entry = f"## {author} ({role}{suffix}) - {stamp}\n{body.strip()}\n\n"
    atomic_write_text(path, existing.rstrip() + "\n\n" + entry)


def _next_stamp(path: Path) -> str:
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    count = existing.count("\n## ") + (1 if existing.startswith("## ") else 0)
    second = count % 60
    minute = (count // 60) % 60
    return f"00:{minute:02d}:{second:02d}"


def doctor(vault: Path) -> list[DoctorFinding]:
    findings: list[DoctorFinding] = []
    required = [
        "pack.yaml",
        "people",
        "lore-bible/canon.md",
        "lore-bible/glossary.md",
        "arcs",
        "episodes",
        ".room",
    ]
    for item in required:
        path = vault / item
        if not path.exists():
            findings.append(DoctorFinding("error", item, "Required vault path is missing."))
    if (vault / "people").exists() and not list((vault / "people").glob("*.md")):
        findings.append(DoctorFinding("error", "people", "At least one personality file is required."))
    pack = vault / "pack.yaml"
    if pack.exists() and "schema:" not in pack.read_text(encoding="utf-8"):
        findings.append(DoctorFinding("error", "pack.yaml", "pack.yaml must declare schema."))
    return findings


def arc_beats(vault: Path) -> list[ArcBeat]:
    arcs_dir = vault / "arcs"
    if not arcs_dir.is_dir():
        return []
    pattern = re.compile(r"^-\s*(S\d+E\d+)\s+\[([^\]]+)\]\s+(.+)$", flags=re.IGNORECASE)
    results: list[ArcBeat] = []
    for path in sorted(arcs_dir.glob("*.md")):
        slug = path.stem
        for raw in path.read_text(encoding="utf-8").splitlines():
            match = pattern.match(raw.strip())
            if match:
                results.append(
                    ArcBeat(
                        arc=slug,
                        episode=match.group(1).upper(),
                        status=match.group(2).strip(),
                        beat=match.group(3).strip(),
                        file=path,
                    )
                )
    return results


def _arc_file(vault: Path, arc_slug: str) -> Path:
    return vault / "arcs" / f"{slugify(arc_slug)}.md"


def _arc_line(episode_id: str, status: str, beat: str) -> str:
    return f"- {episode_id.upper()} [{status.strip()}] {beat.strip()}"


def add_arc_beat(vault: Path, arc_slug: str, episode_id: str, status: str, beat: str) -> Path:
    path = _arc_file(vault, arc_slug)
    if not path.exists():
        title = arc_slug.replace("-", " ").title()
        atomic_write_text(path, f"# {title}\n\n")
    body = path.read_text(encoding="utf-8")
    if "## Episode Beats" not in body:
        body = body.rstrip() + "\n\n## Episode Beats\n\n"
    elif not body.endswith("\n"):
        body += "\n"
    atomic_write_text(path, body + _arc_line(episode_id, status, beat) + "\n")
    return path


def update_arc_beat(
    vault: Path,
    *,
    arc_slug: str,
    episode_id: str,
    original_beat: str,
    new_episode_id: str,
    new_status: str,
    new_beat: str,
) -> Path:
    path = _arc_file(vault, arc_slug)
    if not path.exists():
        raise VaultError(f"arc not found: {arc_slug}")
    text = path.read_text(encoding="utf-8")
    new_text, count = _replace_arc_line(text, episode_id, original_beat, _arc_line(new_episode_id, new_status, new_beat))
    if count == 0:
        raise VaultError(f"arc beat not found in {arc_slug}: {episode_id} {original_beat!r}")
    atomic_write_text(path, new_text)
    return path


def remove_arc_beat(vault: Path, arc_slug: str, episode_id: str, beat: str) -> Path:
    path = _arc_file(vault, arc_slug)
    if not path.exists():
        raise VaultError(f"arc not found: {arc_slug}")
    text = path.read_text(encoding="utf-8")
    new_text, count = _replace_arc_line(text, episode_id, beat, replacement=None)
    if count == 0:
        raise VaultError(f"arc beat not found in {arc_slug}: {episode_id} {beat!r}")
    atomic_write_text(path, new_text)
    return path


def _replace_arc_line(
    text: str,
    episode_id: str,
    beat: str,
    replacement: str | None,
) -> tuple[str, int]:
    pattern = re.compile(
        rf"^-\s*(?i:{re.escape(episode_id.upper())})\s+\[[^\]]+\]\s+{re.escape(beat.strip())}[ \t]*$",
        flags=re.MULTILINE,
    )
    if replacement is None:
        new_text, count = pattern.subn("", text)
        new_text = re.sub(r"\n{3,}", "\n\n", new_text)
        return new_text, count
    return pattern.subn(replacement, text)


def copy_episode(vault: Path, source_id: str, target_id: str) -> Path:
    source = vault / "episodes" / source_id
    target = vault / "episodes" / target_id
    if not source.exists():
        raise VaultError(f"Episode not found: {source_id}")
    if target.exists():
        raise VaultError(f"Episode already exists: {target_id}")
    shutil.copytree(source, target)
    meta = episode_meta(target)
    meta["episode"] = target_id
    meta["forked_from"] = source_id
    write_episode_meta(target, meta)
    return target


_LORE_FACT_RE = re.compile(
    r"^-\s*(?:\*\*Manual fact\*\*\s*-\s*)?(.+?)(?:\s*\*Source:\s*([^*]+?)\s*\*)?\s*$"
)


def lore_facts(vault: Path) -> list[LoreFact]:
    canon = vault / "lore-bible" / "canon.md"
    if not canon.exists():
        return []
    in_facts = False
    results: list[LoreFact] = []
    for raw in canon.read_text(encoding="utf-8").splitlines():
        line = raw.rstrip()
        stripped = line.lstrip()
        if stripped.startswith("## "):
            in_facts = stripped.lower().startswith("## facts")
            continue
        if not in_facts:
            continue
        match = _LORE_FACT_RE.match(stripped)
        if not match:
            continue
        text = match.group(1).strip()
        source = (match.group(2) or "manual").strip()
        if text:
            results.append(LoreFact(text=text, source=source, file=canon))
    return results


def _canon_path(vault: Path) -> Path:
    return vault / "lore-bible" / "canon.md"


def _lore_line(text: str, source: str) -> str:
    return f"- **Manual fact** - {text.strip()} *Source: {source.strip() or 'manual'}*"


def add_lore_fact(vault: Path, text: str, *, source: str = "manual") -> Path:
    path = _canon_path(vault)
    body = path.read_text(encoding="utf-8") if path.exists() else "# Canon\n\n## Facts\n\n"
    if "## Facts" not in body:
        body = body.rstrip() + "\n\n## Facts\n\n"
    body = body.rstrip() + "\n" + _lore_line(text, source) + "\n"
    atomic_write_text(path, body)
    return path


def update_lore_fact(
    vault: Path,
    *,
    original_text: str,
    new_text: str,
    new_source: str,
) -> Path:
    path = _canon_path(vault)
    if not path.exists():
        raise VaultError("canon.md missing")
    text = path.read_text(encoding="utf-8")
    new_body, count = _replace_lore_line(text, original_text, _lore_line(new_text, new_source))
    if count == 0:
        raise VaultError(f"lore fact not found: {original_text!r}")
    atomic_write_text(path, new_body)
    return path


def remove_lore_fact(vault: Path, text: str) -> Path:
    path = _canon_path(vault)
    if not path.exists():
        raise VaultError("canon.md missing")
    body = path.read_text(encoding="utf-8")
    new_body, count = _replace_lore_line(body, text, replacement=None)
    if count == 0:
        raise VaultError(f"lore fact not found: {text!r}")
    atomic_write_text(path, new_body)
    return path


def _replace_lore_line(
    text: str,
    fact: str,
    replacement: str | None,
) -> tuple[str, int]:
    pattern = re.compile(
        rf"^-\s*(?:\*\*Manual fact\*\*\s*-\s*)?{re.escape(fact.strip())}(?:\s*\*Source:[^*]*\*)?[ \t]*$",
        flags=re.MULTILINE,
    )
    if replacement is None:
        new_text, count = pattern.subn("", text)
        new_text = re.sub(r"\n{3,}", "\n\n", new_text)
        return new_text, count
    return pattern.subn(replacement, text)
