from __future__ import annotations

import json
import os
import re
import shutil
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any


class VaultError(RuntimeError):
    """Raised when the requested vault operation cannot be completed."""


@dataclass(frozen=True)
class DoctorFinding:
    level: str
    path: str
    message: str


DEFAULT_PACK = """schema: 1
show:
  name: {show_name}
  eras: []
  genre: speculative fiction
  tone: character-forward, dramatic, collaborative
season:
  number: 1
  episode_count: 10
  theme: "A room discovers what the show wants to become."
  arc_spine:
    - episode_target: 1
      beat: pilot - establish theme
roles:
  - kind: showrunner
    person: showrunner
  - kind: director
    person: director
  - kind: writer
    person: staff-writer
provider:
  default: mock
  fallback: mock
budget:
  max_dollars_per_episode: 5.00
"""

DEFAULT_PEOPLE = {
    "showrunner": """---
schema: 1
slug: showrunner
display_name: Showrunner
roles_eligible: [showrunner]
voice:
  fingerprint: "clear theme, decisive taste, protects the season spine"
  signature_moves:
    - "ties every idea back to the season theme"
beliefs:
  - "A strong episode argues with the season theme."
bio_anchors:
  - "Synthetic starter persona generated by ShowBible."
trait_axes:
  openness: 0.8
  conscientiousness: 0.8
  extraversion: 0.5
  agreeableness: 0.6
  neuroticism: 0.3
---

# Showrunner - relationships

## With Director
Trusts the Director to turn premise into playable scenes.
""",
    "director": """---
schema: 1
slug: director
display_name: Director
roles_eligible: [director]
voice:
  fingerprint: "practical, visual, scene-focused"
  signature_moves:
    - "turns abstract ideas into act breaks"
beliefs:
  - "Conflict belongs on screen, not just in exposition."
bio_anchors:
  - "Synthetic starter persona generated by ShowBible."
trait_axes:
  openness: 0.7
  conscientiousness: 0.7
  extraversion: 0.6
  agreeableness: 0.5
  neuroticism: 0.4
---

# Director - relationships

## With Showrunner
Pushes for playable scenes while honoring the season spine.
""",
    "staff-writer": """---
schema: 1
slug: staff-writer
display_name: Staff Writer
roles_eligible: [writer]
voice:
  fingerprint: "curious, connective, good with reversals"
  signature_moves:
    - "finds the emotional turn inside a scene"
beliefs:
  - "Dialogue should reveal pressure, not explain plot."
bio_anchors:
  - "Synthetic starter persona generated by ShowBible."
trait_axes:
  openness: 0.9
  conscientiousness: 0.6
  extraversion: 0.6
  agreeableness: 0.7
  neuroticism: 0.4
---

# Staff Writer - relationships

## With Director
Offers playable alternatives when a scene stalls.
""",
}


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "show"


def atomic_write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp_name, path)
    finally:
        tmp_path = Path(tmp_name)
        if tmp_path.exists():
            tmp_path.unlink()


def atomic_write_json(path: Path, data: Any) -> None:
    atomic_write_text(path, json.dumps(data, indent=2, sort_keys=True) + "\n")


def read_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def is_vault(path: Path) -> bool:
    return (path / "pack.yaml").is_file()


def discover_vault(start: Path | None = None) -> Path:
    current = (start or Path.cwd()).resolve()
    if current.is_file():
        current = current.parent
    for candidate in [current, *current.parents]:
        if is_vault(candidate):
            return candidate
    raise VaultError("Vault not found. Run inside a ShowBible vault or pass --vault.")


def resolve_vault(path: str | None) -> Path:
    return discover_vault(Path(path)) if path else discover_vault()


def ensure_empty_or_force(path: Path, force: bool) -> None:
    if path.exists() and any(path.iterdir()) and not force:
        raise VaultError(f"Refusing to initialize non-empty directory: {path}")


def init_vault(target: Path, show_name: str | None = None, force: bool = False) -> Path:
    target = target.resolve()
    ensure_empty_or_force(target, force)
    target.mkdir(parents=True, exist_ok=True)

    show = show_name or target.name.replace("-", " ").replace("_", " ").title()
    for directory in [
        "research",
        "people",
        "lore-bible",
        "arcs",
        "episodes",
        ".room/sessions",
        ".room/locks",
        ".room/interventions",
    ]:
        (target / directory).mkdir(parents=True, exist_ok=True)

    atomic_write_text(target / "pack.yaml", DEFAULT_PACK.format(show_name=show))
    atomic_write_text(target / "research" / "sources.md", f"# Sources for {show}\n\n- Seeded locally by ShowBible.\n")
    atomic_write_text(target / "research" / "notes.md", f"# Research Notes for {show}\n\nStarter pack created without external research.\n")
    for slug, content in DEFAULT_PEOPLE.items():
        atomic_write_text(target / "people" / f"{slug}.md", content)
    atomic_write_text(target / "lore-bible" / "canon.md", "# Canon\n\n## Facts\n\n- No canon facts recorded yet.\n")
    atomic_write_text(target / "lore-bible" / "glossary.md", "# Glossary\n\n")
    atomic_write_text(target / "lore-bible" / "relationships.md", "# Relationships\n\n")
    atomic_write_text(
        target / "arcs" / "season-theme.md",
        "---\nschema: 1\nseason: 1\nbeats:\n  - episode_target: 1\n    beat: establish the room's central argument\n    status: planned\n---\n\n# Season Theme\n\nA starter arc for the first season.\n",
    )
    atomic_write_json(target / ".room" / "costs.json", {"episodes": {}, "total_tokens": 0, "total_dollars": 0.0})
    atomic_write_json(target / ".room" / "state.json", {"schema": 1, "status": "initialized"})
    return target


def people(vault: Path) -> list[dict[str, str]]:
    result: list[dict[str, str]] = []
    for path in sorted((vault / "people").glob("*.md")):
        text = path.read_text(encoding="utf-8")
        display = _frontmatter_value(text, "display_name") or path.stem.replace("-", " ").title()
        result.append({"slug": path.stem, "display_name": display})
    return result


def _frontmatter_value(text: str, key: str) -> str | None:
    match = re.search(rf"^{re.escape(key)}:\s*(.+)$", text, flags=re.MULTILINE)
    if not match:
        return None
    return match.group(1).strip().strip("\"'")


def ensure_episode(vault: Path, episode_id: str) -> Path:
    episode = vault / "episodes" / episode_id
    for directory in ["writers-room", "drafts"]:
        (episode / directory).mkdir(parents=True, exist_ok=True)
    meta = episode / "meta.json"
    if not meta.exists():
        atomic_write_json(
            meta,
            {
                "schema": 1,
                "episode": episode_id,
                "status": "created",
                "completed_phases": [],
                "phase_events": [],
                "interventions": [],
            },
        )
    return episode


def list_episodes(vault: Path) -> list[str]:
    episodes_dir = vault / "episodes"
    if not episodes_dir.exists():
        return []
    return sorted(path.name for path in episodes_dir.iterdir() if path.is_dir())


def episode_meta(episode: Path) -> dict[str, Any]:
    return read_json(
        episode / "meta.json",
        {
            "schema": 1,
            "episode": episode.name,
            "status": "created",
            "completed_phases": [],
            "phase_events": [],
            "interventions": [],
        },
    )


def write_episode_meta(episode: Path, meta: dict[str, Any]) -> None:
    atomic_write_json(episode / "meta.json", meta)


def append_transcript_entry(path: Path, author: str, role: str, body: str, intervention: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        atomic_write_text(path, "---\nschema: 1\n---\n\n")
    stamp = _next_stamp(path)
    suffix = ", intervention" if intervention else ""
    existing = path.read_text(encoding="utf-8")
    entry = f"## {author} ({role}{suffix}) - {stamp}\n{body.strip()}\n\n"
    atomic_write_text(path, existing.rstrip() + "\n\n" + entry)


def _next_stamp(path: Path) -> str:
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    count = existing.count("\n## ") + (1 if existing.startswith("## ") else 0)
    second = count % 60
    minute = (count // 60) % 60
    return f"00:{minute:02d}:{second:02d}"


def doctor(vault: Path) -> list[DoctorFinding]:
    findings: list[DoctorFinding] = []
    required = [
        "pack.yaml",
        "people",
        "lore-bible/canon.md",
        "lore-bible/glossary.md",
        "arcs",
        "episodes",
        ".room",
    ]
    for item in required:
        path = vault / item
        if not path.exists():
            findings.append(DoctorFinding("error", item, "Required vault path is missing."))
    if (vault / "people").exists() and not list((vault / "people").glob("*.md")):
        findings.append(DoctorFinding("error", "people", "At least one personality file is required."))
    pack = vault / "pack.yaml"
    if pack.exists() and "schema:" not in pack.read_text(encoding="utf-8"):
        findings.append(DoctorFinding("error", "pack.yaml", "pack.yaml must declare schema."))
    return findings


def copy_episode(vault: Path, source_id: str, target_id: str) -> Path:
    source = vault / "episodes" / source_id
    target = vault / "episodes" / target_id
    if not source.exists():
        raise VaultError(f"Episode not found: {source_id}")
    if target.exists():
        raise VaultError(f"Episode already exists: {target_id}")
    shutil.copytree(source, target)
    meta = episode_meta(target)
    meta["episode"] = target_id
    meta["forked_from"] = source_id
    write_episode_meta(target, meta)
    return target
